# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04-arm

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Linux 源码
        uses: actions/checkout@v4
        with:
          repository: msm8953-mainline/linux
          ref: v6.12.0-r2
          path: linux

      - name: 安装依赖
        run: |
          sudo apt install gcc-aarch64-linux-gnu
          sudo apt install bison flex libncurses-dev make libssl-dev u-boot-tools curl build-essential debhelper-compat libelf-dev

      - name: 拉取config
        #run: curl https://raw.githubusercontent.com/TC999/redmi6pro-linux/refs/heads/main/.config -o linux/.config
      #  run: curl https://gist.githubusercontent.com/TC999/05de52fedac2818dc2cadf207e748fdb/raw/40eebaae07b085646b02027f6153949c423bbc46/.config -o linux/.config
        run: mv .config linux/.config

      - name: 编译
        run: cd linux && make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- deb-pkg -j$(nproc)

      - name: 移动
        run: find . -type f -name "*.deb" -exec cp {} . \;

      - name: 上传
        uses: actions/upload-artifact@v4.6.0
        with:
          path: |
            *.deb
            linux/arch/arm64/boot
            linux/vmlinux
